//
// Generated file, do not edit! Created by nedtool 4.6 from MyPckt.msg.
//

#ifndef _MYPCKT_M_H_
#define _MYPCKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MyPckt.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet MyPckt
 * {
 *     int id;
 *     char type;
 * }
 * </pre>
 */
class MyPckt : public ::cPacket
{
  protected:
    int id_var;
    char type_var;

  private:
    void copy(const MyPckt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyPckt&);

  public:
    MyPckt(const char *name=NULL, int kind=0);
    MyPckt(const MyPckt& other);
    virtual ~MyPckt();
    MyPckt& operator=(const MyPckt& other);
    virtual MyPckt *dup() const {return new MyPckt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual char getType() const;
    virtual void setType(char type);
};

inline void doPacking(cCommBuffer *b, MyPckt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MyPckt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MYPCKT_M_H_

